### PR TITLE
Assignment 4

### PR DESCRIPTION
**Pull request by kathieroy**
…Assignment 4, first pass.  Having trouble understanding where I would… put the @NotNull and @Immutable

### CODE REVIEW

**Comment by kathieroy** [comment]
ok, CircleCi passes now

**Comment by smarks** [comment]
only seven tests - seems light.

**Review by smarks — COMMENTED** [review]
https://stefanbirkner.github.io/system-rules/

**Comment by kathieroy** [comment]
merging so that I can move on to Assignment 5

**Pull request merged**
